name: Deploy to EC2

on:
  push:
    branches:
      - main   

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install node modules
        run: npm ci --legacy-peer-deps

      - name: Run build
        run: npm run build

      - name: Connect to EC2 Instance
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem
        


      


     